name: alpha-mind-integration

networks:
  alpha-mind-network:
    driver: bridge

services:
  firestore:
    extends:
      file: ../docker-compose.yml
      service: firestore

  pubsub:
    extends:
      file: ../docker-compose.yml
      service: pubsub

  gcs:
    extends:
      file: ../docker-compose.yml
      service: gcs

  init:
    extends:
      file: ../docker-compose.yml
      service: init
