allOf:
- "$ref": "./index.yaml#/StrategySettings"
example:
  market: JP
  rebalanceFrequency: daily
  symbols:
  - 1306.T
  - 1321.T
  - 1348.T
  - 1475.T
  - 2558.T
  dailyLossLimit: 0.0
  positionConcentrationLimit: 0.0
  dailyOrderLimit: 1
